[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
OutputCollectors = "6c11c7d4-943b-4e2b-80de-f2cfc2930a8c"

[compat]
JSON = "1"
